spring:
  datasource:
    url: jdbc:h2:mem:session-db;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    generate-unique-name: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-allow-others: true
      path: /h2-console
  # https://docs.spring.io/spring-session/reference/guides/boot-jdbc.html
  session:
    jdbc:
      initialize-schema: embedded
      table-name: SPRING_SESSION
  sql:
    init:
      schema-locations: classpath:org/springframework/session/jdbc/schema-h2.sql
